degree_clusters = {

    "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE WITH IT)": {
        "universities": [


    {
        "PROG CODE": "1053107",
        "INSTITUTION NAME": "JARAMOGI OGINGA ODINGA UNIVERSITY OF SCIENCE AND TECHNOLOGY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE WITH IT)",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1057107",
        "INSTITUTION NAME": "EGERTON UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE)",
        "2023CUTOFF": 32.262
    },
    {
        "PROG CODE": "1087107",
        "INSTITUTION NAME": "KISII UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1111107",
        "INSTITUTION NAME": "KENYATTA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE)",
        "2023CUTOFF": 34.474
    },
    {
        "PROG CODE": "1114107",
        "INSTITUTION NAME": "UNIVERSITY OF ELDORET",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 23.568
    },
    {
        "PROG CODE": "1118107",
        "INSTITUTION NAME": "UNIVERSITY OF KABIANGA",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE)",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1164107",
        "INSTITUTION NAME": "MULTIMEDIA UNIVERSITY OF KENYA",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 28.075
    },
    {
        "PROG CODE": "1166107",
        "INSTITUTION NAME": "SOUTH EASTERN KENYA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE)",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1173107",
        "INSTITUTION NAME": "DEDAN KIMATHI UNIVERSITY OF TECHNOLOGY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 24.443
    },
    {
        "PROG CODE": "1229107",
        "INSTITUTION NAME": "MASENO UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE, WITH IT)",
        "2023CUTOFF": 26.81
    },
    {
        "PROG CODE": "1240107",
        "INSTITUTION NAME": "MERU UNIVERSITY OF SCIENCE AND TECHNOLOGY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE)",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1244107",
        "INSTITUTION NAME": "KARATINA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1249107",
        "INSTITUTION NAME": "JOMO KENYATTA UNIVERSITY OF AGRICULTURE AND TECHNOLOGY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 34.347
    },
    {
        "PROG CODE": "1253107",
        "INSTITUTION NAME": "MOI UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE)",
        "2023CUTOFF": 24.905
    },
    {
        "PROG CODE": "1263107",
        "INSTITUTION NAME": "UNIVERSITY OF NAIROBI",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE)",
        "2023CUTOFF": 39.531
    },
    {
        "PROG CODE": "1162107",
        "INSTITUTION NAME": "DAYSTAR UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1279107",
        "INSTITUTION NAME": "MOUNT KENYA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1480107",
        "INSTITUTION NAME": "CATHOLIC UNIVERSITY OF EASTERN AFRICA",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1079107",
        "INSTITUTION NAME": "KIRINYAGA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1096107",
        "INSTITUTION NAME": "GARISSA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE)",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1246107",
        "INSTITUTION NAME": "MURANG'A UNIVERSITY OF TECHNOLOGY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1515107",
        "INSTITUTION NAME": "TOM MBOYA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE, WITH IT)",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1061107",
        "INSTITUTION NAME": "KABARAK UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1103107",
        "INSTITUTION NAME": "KCA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1105107",
        "INSTITUTION NAME": "CHUKA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 25.416
    },
    {
        "PROG CODE": "1170107",
        "INSTITUTION NAME": "MACHAKOS UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE (ACTUARIAL SCIENCE)",
        "2023CUTOFF": 23.617
    },
    {
        "PROG CODE": "1685107",
        "INSTITUTION NAME": "THARAKA UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    },
    {
        "PROG CODE": "1080107",
        "INSTITUTION NAME": "CO-OPERATIVE UNIVERSITY OF KENYA",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 25.061
    },
    {
        "PROG CODE": "1425107",
        "INSTITUTION NAME": "ZETECH UNIVERSITY",
        "PROGRAMME NAME": "BACHELOR OF SCIENCE IN ACTUARIAL SCIENCE",
        "2023CUTOFF": 18.831
    }],
        "core_subjects": ["Math", "English", "Physics", "Computer Studies"],
        "min_grades": {"Math": "C+", "English": "C", "Physics": "C", "Computer Studies": "C+"}
    },






    # Add more courses with their requirements
}
